base_url = "https://404salad.github.io/webring/"
ring_name = "Webring"
ring_description = "a webring for friends"
ring_owner = "404salad"
ring_owner_site = "https://aboutsahil.vercel.app/"

filepath_list = "./websites.json"
path_output = "./webring"
path_assets = "./data/assets"
path_templates = "./data/templates"
filename_template_redirect = "template.html"

client_user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
client_header = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
audit_retries_delay = 100
audit_retries_max = 2

shuffle = false
verbose = false
skip_minify = false
skip_verify = false
dry_run = false
